const RentalItem = require('../src/models/RentalItem');
const RentalBooking = require('../src/models/RentalBooking');
const { sequelize } = require('../src/config/db');
const dotenv = require('dotenv');

const path = require('path');
dotenv.config({ path: path.resolve(__dirname, '../src/.env') });

const RENTAL_ITEMS = [
  // 1. Digital devices (10 Items)
  {
    id: 'dig-1',
    category: 'digital-devices',
    title: 'Sony Alpha A7 IV 4K Mirrorless Camera Kit',
    dailyPrice: 4500,
    specs: ['4K 60fps', '33MP Full-Frame', '128GB SD', '2x Batteries'],
    description: 'Top-tier hybrid 4K camera for cinema video shooting and portrait photography.',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Kasun Perera',
    ownerEmail: 'kasun.p@gmail.com',
    ownerPhone: '+94 77 123 4567',
    ownerId: 'owner_kasun',
    deposit: 10000,
    status: 'active'
  },
  {
    id: 'dig-2',
    category: 'digital-devices',
    title: 'Canon EOS 90D DSLR Camera Kit',
    dailyPrice: 3500,
    specs: ['32.5MP APS-C', '4K Video', '18-135mm Lens', 'Extra Battery'],
    description: 'Ideal DSLR camera for campus documentary projects, sports coverage, and photojournalism.',
    image: 'https://images.unsplash.com/photo-1519638399535-1b036603ac77?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Dinuka Silva',
    ownerEmail: 'dinuka.s@gmail.com',
    ownerPhone: '+94 71 987 6543',
    ownerId: 'owner_dinuka',
    deposit: 8000,
    status: 'active'
  },
  {
    id: 'dig-3',
    category: 'digital-devices',
    title: 'Nikon Z6 II Full-Frame Mirrorless Camera',
    dailyPrice: 3800,
    specs: ['24.5MP Sensor', 'Dual EXPEED 6', '4K 60p', '24-70mm Lens'],
    description: 'Versatile mirrorless camera with excellent low-light performance for events.',
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Sahan Jayawardena',
    ownerEmail: 'sahan.j@gmail.com',
    ownerPhone: '+94 78 999 0011',
    ownerId: 'owner_sahan',
    deposit: 8500,
    status: 'active'
  },
  {
    id: 'dig-4',
    category: 'digital-devices',
    title: 'Fujifilm X-T4 4K Video Camera & Lens',
    dailyPrice: 3200,
    specs: ['In-Body Stabilization', '4K 60p 10-Bit', 'Film Simulation'],
    description: 'Compact hybrid video camera with film color simulation profiles.',
    image: 'https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Lankanath Rodrigo',
    ownerEmail: 'lankanath.r@gmail.com',
    ownerPhone: '+94 71 777 5511',
    ownerId: 'owner_lankanath',
    deposit: 7000,
    status: 'active'
  },
  {
    id: 'dig-5',
    category: 'digital-devices',
    title: 'GoPro Hero 11 Black 4K Action Camera',
    dailyPrice: 1500,
    specs: ['5.3K Video', 'HyperSmooth 5.0', 'Waterproof 10m', 'Mounts'],
    description: 'Rugged waterproof action camera for outdoor sports, travel vlogging, and adventure.',
    image: 'https://images.unsplash.com/photo-1564466809058-bf4114d55352?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Malith Fernando',
    ownerEmail: 'malith.f@gmail.com',
    ownerPhone: '+94 75 456 7890',
    ownerId: 'owner_malith',
    deposit: 4000,
    status: 'active'
  },
  {
    id: 'dig-6',
    category: 'digital-devices',
    title: 'Epson Pro Full HD 1080p 4000 Lumens Projector',
    dailyPrice: 2800,
    specs: ['4,000 Lumens', 'Full HD 1080p', 'Wireless Mirroring', 'HDMI'],
    description: 'Ultra-bright projector suitable for lecture halls, presentation slides, and movie nights.',
    image: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Dinuka Silva',
    ownerEmail: 'dinuka.s@gmail.com',
    ownerPhone: '+94 71 987 6543',
    ownerId: 'owner_dinuka',
    deposit: 6000,
    status: 'active'
  },
  {
    id: 'dig-7',
    category: 'digital-devices',
    title: 'Anker Nebula Capsule Mini Portable Projector',
    dailyPrice: 1800,
    specs: ['Pocket Sized', '360° Speaker', '4h Battery', 'Android TV'],
    description: 'Ultra-compact soda-can sized projector. Project anywhere onto any clean wall.',
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Nisala Wickramasinghe',
    ownerEmail: 'nisala.w@gmail.com',
    ownerPhone: '+94 75 222 9900',
    ownerId: 'owner_nisala',
    deposit: 4000,
    status: 'active'
  },
  {
    id: 'dig-8',
    category: 'digital-devices',
    title: 'BenQ MH535FHD High Brightness Projector',
    dailyPrice: 2400,
    specs: ['3600 ANSI Lumens', '1080p Native', 'Dual HDMI Ports'],
    description: 'Crisp presentation projector optimized for detailed engineering diagrams.',
    image: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Tharindu Gamage',
    ownerEmail: 'tharindu.g@gmail.com',
    ownerPhone: '+94 71 222 4455',
    ownerId: 'owner_tharindu',
    deposit: 5000,
    status: 'active'
  },
  {
    id: 'dig-9',
    category: 'digital-devices',
    title: 'DJI Ronin SC 3-Axis Motorized Camera Gimbal',
    dailyPrice: 1600,
    specs: ['3-Axis Stabilization', '2.0kg Payload', 'Focus Wheel'],
    description: 'Smooth motorized stabilization for mirrorless cameras during dynamic handheld shoots.',
    image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Malith Fernando',
    ownerEmail: 'malith.f@gmail.com',
    ownerPhone: '+94 75 456 7890',
    ownerId: 'owner_malith',
    deposit: 3500,
    status: 'active'
  },
  {
    id: 'dig-10',
    category: 'digital-devices',
    title: 'JBL PartyBox 310 Portable Bluetooth Speaker',
    dailyPrice: 2500,
    specs: ['240W RMS Output', 'RGB Lightshow', '18h Battery', 'Wheels'],
    description: 'High power party speaker with deep bass, microphone inputs, and Bluetooth pairing.',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Akila Karunaratne',
    ownerEmail: 'akila.k@gmail.com',
    ownerPhone: '+94 77 999 1234',
    ownerId: 'owner_akila',
    deposit: 5000,
    status: 'active'
  },

  // 2. Computers and computer accessories (10 Items)
  {
    id: 'cmp-1',
    category: 'computers-and-computer-accessories',
    title: 'Apple MacBook Pro 16" M2 Pro Workstation',
    dailyPrice: 5500,
    specs: ['32GB RAM', '1TB NVMe SSD', 'Liquid Retina XDR', 'MagSafe'],
    description: 'Powerhouse machine for video editing, iOS development, machine learning, & rendering.',
    image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Kavindu Rathnayake',
    ownerEmail: 'kavindu.r@gmail.com',
    ownerPhone: '+94 76 222 3344',
    ownerId: 'owner_kavindu',
    deposit: 15000,
    status: 'active'
  },
  {
    id: 'cmp-2',
    category: 'computers-and-computer-accessories',
    title: 'Dell XPS 15 9530 Core i9 Workstation Laptop',
    dailyPrice: 4800,
    specs: ['Intel Core i9', 'RTX 4060 GPU', '32GB DDR5', '3.5K OLED'],
    description: 'Premium Windows laptop with dedicated graphics for CAD modeling, Unity, & Unreal Engine.',
    image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Tharindu Gamage',
    ownerEmail: 'tharindu.g@gmail.com',
    ownerPhone: '+94 71 222 4455',
    ownerId: 'owner_tharindu',
    deposit: 12000,
    status: 'active'
  },
  {
    id: 'cmp-3',
    category: 'computers-and-computer-accessories',
    title: 'Lenovo ThinkPad X1 Carbon Gen 10 Laptop',
    dailyPrice: 3500,
    specs: ['Intel Core i7', '16GB RAM', '512GB SSD', 'Ultra-Light 1.1kg'],
    description: 'Ultra-light business workstation laptop with superb keyboard for programming.',
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Gayan Weerasinghe',
    ownerEmail: 'gayan.w@gmail.com',
    ownerPhone: '+94 71 444 8899',
    ownerId: 'owner_gayan',
    deposit: 9000,
    status: 'active'
  },
  {
    id: 'cmp-4',
    category: 'computers-and-computer-accessories',
    title: 'ASUS ROG Zephyrus G14 Gaming/Rendering Laptop',
    dailyPrice: 4000,
    specs: ['Ryzen 9', 'RTX 3070', '16GB RAM', '120Hz Display'],
    description: 'High refresh rate performance laptop for graphics design and 3D simulation.',
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Charith Mendis',
    ownerEmail: 'charith.m@gmail.com',
    ownerPhone: '+94 77 555 6677',
    ownerId: 'owner_charith',
    deposit: 10000,
    status: 'active'
  },
  {
    id: 'cmp-5',
    category: 'computers-and-computer-accessories',
    title: 'SanDisk 2TB Extreme Portable NVMe SSD',
    dailyPrice: 450,
    specs: ['1050MB/s Speed', 'USB 3.2 Gen 2', 'Drop Resistant'],
    description: 'Ultra-fast NVMe portable SSD drive for high speed video and project data backup.',
    image: 'https://images.unsplash.com/photo-1544652478-6653e09f18a2?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Chathura Bandara',
    ownerEmail: 'chathura.b@gmail.com',
    ownerPhone: '+94 70 111 2233',
    ownerId: 'owner_chathura',
    deposit: 1500,
    status: 'active'
  },
  {
    id: 'cmp-6',
    category: 'computers-and-computer-accessories',
    title: 'LaCie Rugged Mini 4TB External Hard Drive',
    dailyPrice: 350,
    specs: ['4TB Capacity', 'Shock & Pressure Proof', 'USB-C'],
    description: 'Heavy duty high capacity drive to back up large datasets & raw files.',
    image: 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Praveen Ranasinghe',
    ownerEmail: 'praveen.r@gmail.com',
    ownerPhone: '+94 72 333 4455',
    ownerId: 'owner_praveen',
    deposit: 1200,
    status: 'active'
  },
  {
    id: 'cmp-7',
    category: 'computers-and-computer-accessories',
    title: 'Samsung T7 Shield 1TB NVMe Portable SSD',
    dailyPrice: 300,
    specs: ['1050MB/s', 'Rubber Bumper', 'Hardware Encrypted'],
    description: 'Rugged portable drive ideal for storing final year project data.',
    image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Kavindu Rathnayake',
    ownerEmail: 'kavindu.r@gmail.com',
    ownerPhone: '+94 76 222 3344',
    ownerId: 'owner_kavindu',
    deposit: 1000,
    status: 'active'
  },
  {
    id: 'cmp-8',
    category: 'computers-and-computer-accessories',
    title: 'Logitech MX Master 3S Wireless Ergonomic Mouse',
    dailyPrice: 250,
    specs: ['8K DPI Track', 'Quiet Clicks', 'MagSpeed Scroll'],
    description: 'Precision wireless ergonomic mouse for software developers & designers.',
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Praveen Ranasinghe',
    ownerEmail: 'praveen.r@gmail.com',
    ownerPhone: '+94 72 333 4455',
    ownerId: 'owner_praveen',
    deposit: 800,
    status: 'active'
  },
  {
    id: 'cmp-9',
    category: 'computers-and-computer-accessories',
    title: 'Keychron K2 Mechanical Wireless Keyboard',
    dailyPrice: 300,
    specs: ['Gateron Brown Switches', 'RGB Backlight', 'Bluetooth 5.1'],
    description: 'Tactile mechanical keyboard for typing speed and coding accuracy.',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Isuru Fonseka',
    ownerEmail: 'isuru.f@gmail.com',
    ownerPhone: '+94 77 888 1122',
    ownerId: 'owner_isuru',
    deposit: 1000,
    status: 'active'
  },
  {
    id: 'cmp-10',
    category: 'computers-and-computer-accessories',
    title: 'Dell UltraSharp 27" 4K Monitor with USB-C Hub',
    dailyPrice: 1500,
    specs: ['4K IPS', '99% sRGB', '90W USB-C PD', 'Adjustable Stand'],
    description: 'Color-accurate 4K monitor for dual-screen productivity & graphic design.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Kasun Perera',
    ownerEmail: 'kasun.p@gmail.com',
    ownerPhone: '+94 77 123 4567',
    ownerId: 'owner_kasun',
    deposit: 5000,
    status: 'active'
  },

  // 3. Mobile accessories (10 Items)
  {
    id: 'mob-1',
    category: 'mobile-accessories',
    title: 'Anker 20,000mAh Power Bank Fast Charger',
    dailyPrice: 220,
    specs: ['20,000mAh', 'PowerIQ 3.0', 'Dual USB-C', 'Fast Charge'],
    description: 'High capacity power bank capable of charging phones 4-5 times.',
    image: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Charith Mendis',
    ownerEmail: 'charith.m@gmail.com',
    ownerPhone: '+94 77 555 6677',
    ownerId: 'owner_charith',
    deposit: 800,
    status: 'active'
  },
  {
    id: 'mob-2',
    category: 'mobile-accessories',
    title: 'Baseus 30,000mAh 65W Laptop & Phone Power Bank',
    dailyPrice: 280,
    specs: ['30,000mAh', '65W Power Delivery', 'Digital Display'],
    description: 'Heavy duty power bank that can power both laptops and smartphones.',
    image: 'https://images.unsplash.com/photo-1622445268465-8438b658a8fc?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Gayan Weerasinghe',
    ownerEmail: 'gayan.w@gmail.com',
    ownerPhone: '+94 71 444 8899',
    ownerId: 'owner_gayan',
    deposit: 1000,
    status: 'active'
  },
  {
    id: 'mob-3',
    category: 'mobile-accessories',
    title: 'Anker 737 GaNPrime 120W USB-C Wall Charger',
    dailyPrice: 250,
    specs: ['120W Output', '2x USB-C + 1x USB-A', 'GaN Tech'],
    description: 'Charge 3 devices simultaneously at maximum speed.',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Charith Mendis',
    ownerEmail: 'charith.m@gmail.com',
    ownerPhone: '+94 77 555 6677',
    ownerId: 'owner_charith',
    deposit: 800,
    status: 'active'
  },
  {
    id: 'mob-4',
    category: 'mobile-accessories',
    title: 'Apple 140W USB-C Adapter + MagSafe 3 Cable',
    dailyPrice: 300,
    specs: ['140W Power', 'MagSafe 3 Braided Cable', '2m Length'],
    description: 'Official fast charger for MacBook Pro 16-inch.',
    image: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Gayan Weerasinghe',
    ownerEmail: 'gayan.w@gmail.com',
    ownerPhone: '+94 71 444 8899',
    ownerId: 'owner_gayan',
    deposit: 1000,
    status: 'active'
  },
  {
    id: 'mob-5',
    category: 'mobile-accessories',
    title: 'Samsung 65W Trio Fast Wall Power Adapter',
    dailyPrice: 200,
    specs: ['65W Max', 'Dual Type-C + USB-A', 'Super Fast Charge'],
    description: 'Versatile travel power adapter for laptops & phones.',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Dinuka Silva',
    ownerEmail: 'dinuka.s@gmail.com',
    ownerPhone: '+94 71 987 6543',
    ownerId: 'owner_dinuka',
    deposit: 700,
    status: 'active'
  },
  {
    id: 'mob-6',
    category: 'mobile-accessories',
    title: 'Bose SoundLink Revolve+ II Portable Bluetooth Speaker',
    dailyPrice: 400,
    specs: ['360° Sound', 'IP55 Water Resistant', '17h Playtime'],
    description: 'Crisp room-filling sound in a portable design with handle.',
    image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Roshen Cooray',
    ownerEmail: 'roshen.c@gmail.com',
    ownerPhone: '+94 72 888 3322',
    ownerId: 'owner_roshen',
    deposit: 1500,
    status: 'active'
  },
  {
    id: 'mob-7',
    category: 'mobile-accessories',
    title: 'Sony Wireless Noise-Cancelling ANC Headphones',
    dailyPrice: 350,
    specs: ['Active Noise Cancellation', '30h Playtime', 'Crisp Bass'],
    description: 'Noise-cancelling wireless headphones for quiet studying.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Sahan Jayawardena',
    ownerEmail: 'sahan.j@gmail.com',
    ownerPhone: '+94 78 999 0011',
    ownerId: 'owner_sahan',
    deposit: 1200,
    status: 'active'
  },
  {
    id: 'mob-8',
    category: 'mobile-accessories',
    title: 'Apple AirPods Pro (2nd Gen) with MagSafe Case',
    dailyPrice: 300,
    specs: ['Active Noise Cancellation', 'Adaptive Audio', 'MagSafe'],
    description: 'In-ear wireless earbuds with active noise cancellation.',
    image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Kasun Perera',
    ownerEmail: 'kasun.p@gmail.com',
    ownerPhone: '+94 77 123 4567',
    ownerId: 'owner_kasun',
    deposit: 1000,
    status: 'active'
  },
  {
    id: 'mob-9',
    category: 'mobile-accessories',
    title: 'MagSafe Magnetic Wireless Car Mount Charger',
    dailyPrice: 200,
    specs: ['15W Fast Charge', 'Strong Magnet', '360° Rotation'],
    description: 'Convenient magnetic phone mount and wireless charger.',
    image: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Chathura Bandara',
    ownerEmail: 'chathura.b@gmail.com',
    ownerPhone: '+94 70 111 2233',
    ownerId: 'owner_chathura',
    deposit: 600,
    status: 'active'
  },
  {
    id: 'mob-10',
    category: 'mobile-accessories',
    title: 'DJI Osmo Mobile 6 Smartphone Gimbal Stabilizer',
    dailyPrice: 450,
    specs: ['3-Axis Gimbal', 'ActiveTrack 5.0', 'Built-in Extension Rod'],
    description: 'Handheld smartphone stabilizer for smooth video recordings.',
    image: 'https://images.unsplash.com/photo-1589492477829-5e65395b66cc?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Malith Fernando',
    ownerEmail: 'malith.f@gmail.com',
    ownerPhone: '+94 75 456 7890',
    ownerId: 'owner_malith',
    deposit: 1500,
    status: 'active'
  },

  // 4. Stationary items (10 Items)
  {
    id: 'stn-1',
    category: 'stationary-items',
    title: 'Casio FX-991EX ClassWiz Scientific Calculator',
    dailyPrice: 200,
    specs: ['552 Functions', 'High-Res Display', 'Solar & Battery', 'Exam Legal'],
    description: 'Must-have scientific calculator for engineering and physical science exams.',
    image: 'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Isuru Fonseka',
    ownerEmail: 'isuru.f@gmail.com',
    ownerPhone: '+94 77 888 1122',
    ownerId: 'owner_isuru',
    deposit: 600,
    status: 'active'
  },
  {
    id: 'stn-2',
    category: 'stationary-items',
    title: 'TI-84 Plus CE Color Graphic Calculator',
    dailyPrice: 350,
    specs: ['Color Display', 'Exam Legal', 'Rechargeable', 'Graphing Apps'],
    description: 'Standard graphic calculator for calculus, matrix algebra, statistics, & physics.',
    image: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Shehan Alwis',
    ownerEmail: 'shehan.a@gmail.com',
    ownerPhone: '+94 71 333 7788',
    ownerId: 'owner_shehan',
    deposit: 1000,
    status: 'active'
  },
  {
    id: 'stn-3',
    category: 'stationary-items',
    title: 'TI-Nspire CX II CAS Graphic Calculator',
    dailyPrice: 450,
    specs: ['CAS Engine', '3D Graphing', 'Color Screen', 'Exam Approved'],
    description: 'Advanced Computer Algebra System calculator for complex differential equations.',
    image: 'https://images.unsplash.com/photo-1632571401005-458e9d244591?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Chathura Bandara',
    ownerEmail: 'chathura.b@gmail.com',
    ownerPhone: '+94 70 111 2233',
    ownerId: 'owner_chathura',
    deposit: 1200,
    status: 'active'
  },
  {
    id: 'stn-4',
    category: 'stationary-items',
    title: 'Casio FX-570ES Plus Natural Display Calculator',
    dailyPrice: 200,
    specs: ['417 Functions', 'Natural Textbook Display', 'Matrix/Vector'],
    description: 'Reliable non-programmable scientific calculator for university midterms.',
    image: 'https://images.unsplash.com/photo-1611125832047-1d7ad1e8e48b?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Dinuka Silva',
    ownerEmail: 'dinuka.s@gmail.com',
    ownerPhone: '+94 71 987 6543',
    ownerId: 'owner_dinuka',
    deposit: 500,
    status: 'active'
  },
  {
    id: 'stn-5',
    category: 'stationary-items',
    title: 'Complete Engineering Drawing & Drafting Kit',
    dailyPrice: 250,
    specs: ['T-Square', 'Set Squares', 'Compass Set', 'Board'],
    description: 'Complete set of engineering drafting instruments for civil & mechanical drawing.',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Nisala Wickramasinghe',
    ownerEmail: 'nisala.w@gmail.com',
    ownerPhone: '+94 75 222 9900',
    ownerId: 'owner_nisala',
    deposit: 800,
    status: 'active'
  },
  {
    id: 'stn-6',
    category: 'stationary-items',
    title: 'Rotring Isograph Technical Drawing Pen Set',
    dailyPrice: 220,
    specs: ['0.25mm / 0.35mm / 0.5mm', 'Refillable Ink', 'High Precision'],
    description: 'Precision technical ink pens for architectural and engineering blueprint drawings.',
    image: 'https://images.unsplash.com/photo-1585336261026-6757f541a674?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Praveen Ranasinghe',
    ownerEmail: 'praveen.r@gmail.com',
    ownerPhone: '+94 72 333 4455',
    ownerId: 'owner_praveen',
    deposit: 700,
    status: 'active'
  },
  {
    id: 'stn-7',
    category: 'stationary-items',
    title: 'Adjustable A2 Desktop Technical Drawing Board',
    dailyPrice: 300,
    specs: ['A2 Size', 'Parallel Motion Ruler', 'Angle Lock'],
    description: 'Portable drafting board with built-in straightedge ruler for design projects.',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Kavindu Rathnayake',
    ownerEmail: 'kavindu.r@gmail.com',
    ownerPhone: '+94 76 222 3344',
    ownerId: 'owner_kavindu',
    deposit: 1000,
    status: 'active'
  },
  {
    id: 'stn-8',
    category: 'stationary-items',
    title: 'HP Prime Graphing Calculator with Touch Screen',
    dailyPrice: 400,
    specs: ['Color Touch Screen', 'CAS Engine', 'Rechargeable'],
    description: 'Full-color touchscreen graphic calculator with computer algebra capability.',
    image: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Shehan Alwis',
    ownerEmail: 'shehan.a@gmail.com',
    ownerPhone: '+94 71 333 7788',
    ownerId: 'owner_shehan',
    deposit: 1200,
    status: 'active'
  },
  {
    id: 'stn-9',
    category: 'stationary-items',
    title: 'Professional Architectural Scale Ruler & Stencil Kit',
    dailyPrice: 200,
    specs: ['Triangular Scale', 'Metric Scales', 'Symbol Templates'],
    description: 'Metric triangular scale ruler set with circle and isometric drafting stencils.',
    image: 'https://images.unsplash.com/photo-1585336261026-6757f541a674?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Gayan Weerasinghe',
    ownerEmail: 'gayan.w@gmail.com',
    ownerPhone: '+94 71 444 8899',
    ownerId: 'owner_gayan',
    deposit: 500,
    status: 'active'
  },
  {
    id: 'stn-10',
    category: 'stationary-items',
    title: 'Digital Vernier Caliper & Micrometer Measuring Kit',
    dailyPrice: 250,
    specs: ['0-150mm Range', '0.01mm Accuracy', 'Stainless Steel'],
    description: 'High precision electronic digital caliper for mechanical measurements and lab experiments.',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Kasun Perera',
    ownerEmail: 'kasun.p@gmail.com',
    ownerPhone: '+94 77 123 4567',
    ownerId: 'owner_kasun',
    deposit: 800,
    status: 'active'
  },

  // 5. Cables (10 Items)
  {
    id: 'cbl-1',
    category: 'cables',
    title: 'Anker 10-in-1 USB-C Multiport Dongle Hub',
    dailyPrice: 300,
    specs: ['Dual 4K HDMI', '100W PD Pass-through', '1Gbps Ethernet', 'SD Reader'],
    description: 'Connect monitors, ethernet, flash drives, and power to any laptop with a single USB-C port.',
    image: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Dileepa Jayasuriya',
    ownerEmail: 'dileepa.j@gmail.com',
    ownerPhone: '+94 77 666 4433',
    ownerId: 'owner_dileepa',
    deposit: 800,
    status: 'active'
  },
  {
    id: 'cbl-2',
    category: 'cables',
    title: 'Belkin Ultra High Speed 8K HDMI 2.1 Cable (3m)',
    dailyPrice: 200,
    specs: ['48Gbps Bandwidth', '8K@60Hz / 4K@120Hz', '3 Meters Long'],
    description: 'High performance HDMI cable for connecting laptops to projectors & monitors.',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Lankanath Rodrigo',
    ownerEmail: 'lankanath.r@gmail.com',
    ownerPhone: '+94 71 777 5511',
    ownerId: 'owner_lankanath',
    deposit: 500,
    status: 'active'
  },
  {
    id: 'cbl-3',
    category: 'cables',
    title: 'Shielded Cat8 Heavy Duty Ethernet Cable (15m)',
    dailyPrice: 200,
    specs: ['40Gbps Speed', 'Snagless RJ45', 'Gold Plated', '15m Length'],
    description: 'Heavy-duty shielded RJ45 cable for zero-latency network connection during hackathons.',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Roshen Cooray',
    ownerEmail: 'roshen.c@gmail.com',
    ownerPhone: '+94 72 888 3322',
    ownerId: 'owner_roshen',
    deposit: 500,
    status: 'active'
  },
  {
    id: 'cbl-4',
    category: 'cables',
    title: 'DisplayPort 1.4 to HDMI 4K@120Hz Converter Cable',
    dailyPrice: 220,
    specs: ['DisplayPort to HDMI', '4K 120Hz Support', 'Aluminum Shell'],
    description: 'Connect desktop GPU DisplayPort output to HDMI monitors & TVs seamlessly.',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Sahan Jayawardena',
    ownerEmail: 'sahan.j@gmail.com',
    ownerPhone: '+94 78 999 0011',
    ownerId: 'owner_sahan',
    deposit: 600,
    status: 'active'
  },
  {
    id: 'cbl-5',
    category: 'cables',
    title: 'USB-C 100W Power Delivery Braided Cable (3m)',
    dailyPrice: 200,
    specs: ['100W Fast Charge', 'E-Marker Chip', '3m Length'],
    description: 'Heavy duty braided USB-C cable for high-power laptop charging.',
    image: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Charith Mendis',
    ownerEmail: 'charith.m@gmail.com',
    ownerPhone: '+94 77 555 6677',
    ownerId: 'owner_charith',
    deposit: 500,
    status: 'active'
  },
  {
    id: 'cbl-6',
    category: 'cables',
    title: 'VGA to HDMI Powered Signal Converter Cable',
    dailyPrice: 200,
    specs: ['VGA Input to HDMI Out', '1080p Resolution', 'Audio Jack'],
    description: 'Connect legacy VGA laptop outputs to modern HDMI projectors.',
    image: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Dinuka Silva',
    ownerEmail: 'dinuka.s@gmail.com',
    ownerPhone: '+94 71 987 6543',
    ownerId: 'owner_dinuka',
    deposit: 500,
    status: 'active'
  },
  {
    id: 'cbl-7',
    category: 'cables',
    title: 'Apple Thunderbolt 4 Pro Braided Cable (2m)',
    dailyPrice: 350,
    specs: ['40Gbps Transfer', '100W Charging', 'DisplayPort Video'],
    description: 'Official Apple Thunderbolt 4 braided cable for ultra-fast SSD data transfers.',
    image: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Kavindu Rathnayake',
    ownerEmail: 'kavindu.r@gmail.com',
    ownerPhone: '+94 76 222 3344',
    ownerId: 'owner_kavindu',
    deposit: 1000,
    status: 'active'
  },
  {
    id: 'cbl-8',
    category: 'cables',
    title: 'USB-C to Dual HDMI Splitter Adaptor (4K Extended)',
    dailyPrice: 280,
    specs: ['Dual HDMI 4K', 'MST Mode', 'Pass-Through Power'],
    description: 'Connect two 4K external monitors to a single USB-C laptop port.',
    image: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Chathura Bandara',
    ownerEmail: 'chathura.b@gmail.com',
    ownerPhone: '+94 70 111 2233',
    ownerId: 'owner_chathura',
    deposit: 800,
    status: 'active'
  },
  {
    id: 'cbl-9',
    category: 'cables',
    title: 'High-Speed USB 3.0 Active Extension Cable (10m)',
    dailyPrice: 200,
    specs: ['10m Length', 'Built-in Signal Booster', 'USB 3.0 5Gbps'],
    description: 'Long distance USB extension cable with active chipset for cameras & sensors.',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Malith Fernando',
    ownerEmail: 'malith.f@gmail.com',
    ownerPhone: '+94 75 456 7890',
    ownerId: 'owner_malith',
    deposit: 500,
    status: 'active'
  },
  {
    id: 'cbl-10',
    category: 'cables',
    title: 'Gigabit USB-C to RJ45 Ethernet Network Adaptor',
    dailyPrice: 220,
    specs: ['1000Mbps Speed', 'Aluminum Shell', 'Plug & Play'],
    description: 'Add a high-speed wired ethernet port to slim laptops without RJ45 ports.',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Praveen Ranasinghe',
    ownerEmail: 'praveen.r@gmail.com',
    ownerPhone: '+94 72 333 4455',
    ownerId: 'owner_praveen',
    deposit: 600,
    status: 'active'
  },

  // 6. Camping items (10 Items)
  {
    id: 'cmpg-1',
    category: 'camping-items',
    title: '4-Person Waterproof Outdoor Camping Tent',
    dailyPrice: 600,
    specs: ['4-Person Capacity', 'Waterproof PU3000', 'Double Layer', 'Easy Setup'],
    description: 'Spacious waterproof camping tent with rainfly cover for outdoor trips & hikes.',
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Akila Karunaratne',
    ownerEmail: 'akila.k@gmail.com',
    ownerPhone: '+94 77 999 1234',
    ownerId: 'owner_akila',
    deposit: 1500,
    status: 'active'
  },
  {
    id: 'cmpg-2',
    category: 'camping-items',
    title: '2-Person Instant Pop-Up Waterproof Dome Tent',
    dailyPrice: 400,
    specs: ['Pop-Up 60s Setup', '2-Person', 'UV Protection'],
    description: 'Quick setup instant dome tent perfect for weekend camping trips.',
    image: 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Isuru Fonseka',
    ownerEmail: 'isuru.f@gmail.com',
    ownerPhone: '+94 77 888 1122',
    ownerId: 'owner_isuru',
    deposit: 1000,
    status: 'active'
  },
  {
    id: 'cmpg-3',
    category: 'camping-items',
    title: 'Rechargeable LED Camping Lantern & Power Lamp',
    dailyPrice: 220,
    specs: ['1000 Lumens', 'USB Rechargeable', 'Power Bank Out', 'IPX4 Waterproof'],
    description: 'Ultra-bright lantern with dimmable light modes and USB phone charging capability.',
    image: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Tharindu Gamage',
    ownerEmail: 'tharindu.g@gmail.com',
    ownerPhone: '+94 71 222 4455',
    ownerId: 'owner_tharindu',
    deposit: 800,
    status: 'active'
  },
  {
    id: 'cmpg-4',
    category: 'camping-items',
    title: 'Waterproof Outdoor Hiking Backpack (60L)',
    dailyPrice: 350,
    specs: ['60L Capacity', 'Ergonomic Support', 'Rain Cover Included'],
    description: 'Heavy duty hiking backpack with padded waist straps and hydration sleeve.',
    image: 'https://images.unsplash.com/photo-1622260614153-03223fb72052?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Malith Fernando',
    ownerEmail: 'malith.f@gmail.com',
    ownerPhone: '+94 75 456 7890',
    ownerId: 'owner_malith',
    deposit: 1000,
    status: 'active'
  },
  {
    id: 'cmpg-5',
    category: 'camping-items',
    title: 'Thermal Insulated Outdoor Sleeping Bag (-5°C Rated)',
    dailyPrice: 250,
    specs: ['3-Season Warmth', 'Mummy Design', 'Lightweight Carry Bag'],
    description: 'Thermal insulated sleeping bag designed for cold mountain camping nights.',
    image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Nisala Wickramasinghe',
    ownerEmail: 'nisala.w@gmail.com',
    ownerPhone: '+94 75 222 9900',
    ownerId: 'owner_nisala',
    deposit: 800,
    status: 'active'
  },
  {
    id: 'cmpg-6',
    category: 'camping-items',
    title: 'Foldable Outdoor Camping Chair with Cup Holder',
    dailyPrice: 200,
    specs: ['Steel Frame', '120kg Capacity', 'Compact Carry Bag'],
    description: 'Comfortable folding camp chair for outdoor relaxation and bonfires.',
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Kasun Perera',
    ownerEmail: 'kasun.p@gmail.com',
    ownerPhone: '+94 77 123 4567',
    ownerId: 'owner_kasun',
    deposit: 500,
    status: 'active'
  },
  {
    id: 'cmpg-7',
    category: 'camping-items',
    title: 'Portable Gas Stove & Outdoor Cooking Cookset',
    dailyPrice: 300,
    specs: ['Piezo Ignition', 'Pots & Pans Included', 'Carry Case'],
    description: 'Compact camping gas burner with lightweight non-stick nesting pots.',
    image: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Dinuka Silva',
    ownerEmail: 'dinuka.s@gmail.com',
    ownerPhone: '+94 71 987 6543',
    ownerId: 'owner_dinuka',
    deposit: 800,
    status: 'active'
  },
  {
    id: 'cmpg-8',
    category: 'camping-items',
    title: 'Heavy-Duty Rechargeable Tactical LED Flashlight',
    dailyPrice: 200,
    specs: ['2000 Lumens', 'Zoomable Beam', 'IPX6 Waterproof'],
    description: 'Super bright handheld flashlight with long beam throw and strobe modes.',
    image: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Shehan Alwis',
    ownerEmail: 'shehan.a@gmail.com',
    ownerPhone: '+94 71 333 7788',
    ownerId: 'owner_shehan',
    deposit: 500,
    status: 'active'
  },
  {
    id: 'cmpg-9',
    category: 'camping-items',
    title: 'Inflatable Air Mattress Pad with Built-in Foot Pump',
    dailyPrice: 250,
    specs: ['Self-Inflating', 'Ergonomic Pillow', 'Tear Resistant'],
    description: 'Compact inflatable sleeping pad for tent comfort and insulation.',
    image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Chathura Bandara',
    ownerEmail: 'chathura.b@gmail.com',
    ownerPhone: '+94 70 111 2233',
    ownerId: 'owner_chathura',
    deposit: 700,
    status: 'active'
  },
  {
    id: 'cmpg-10',
    category: 'camping-items',
    title: 'Waterproof Outdoor Trekking & Hiking Poles Set',
    dailyPrice: 200,
    specs: ['Aluminum 7075', 'Anti-Shock', 'Adjustable Height'],
    description: 'Lightweight telescoping hiking poles for mountain trail stability.',
    image: 'https://images.unsplash.com/photo-1622260614153-03223fb72052?auto=format&fit=crop&w=800&q=80',
    ownerName: 'Sahan Jayawardena',
    ownerEmail: 'sahan.j@gmail.com',
    ownerPhone: '+94 78 999 0011',
    ownerId: 'owner_sahan',
    deposit: 500,
    status: 'active'
  }
];

const seedMySQL = async () => {
  try {
    // Authenticate and sync schemas
    await sequelize.authenticate();
    console.log('Connected to MySQL. Syncing tables...');
    
    // Force recreate tables
    await sequelize.sync({ force: true });
    console.log('Cleared existing tables.');

    // Seed items
    await RentalItem.bulkCreate(RENTAL_ITEMS);
    console.log(`Seeded ${RENTAL_ITEMS.length} equipment rental items successfully!`);

    process.exit(0);
  } catch (error) {
    console.error('Failed to seed MySQL database:', error);
    process.exit(1);
  }
};

seedMySQL();
